DROP TABLE IF EXISTS CAR CASCADE;
CREATE TABLE CAR
(
    id      LONG AUTO_INCREMENT PRIMARY KEY,
    brand   VARCHAR(250) NOT NULL,
    model   VARCHAR(250) NOT NULL,
    year    INTEGER      NOT NULL,
    user_id BIGINT
);